version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      yarn install
      yarn build
      aws s3 sync ./out s3://app.squeaky.ai --delete
      aws cloudfront create-invalidation --distribution-id E2WZLVX1DF65XE --paths "/*"

cache:
  paths:
    - node_modules/**/*
